export const GET_POPULAR_VIDEOS = 'getPopularVideo'
export const GET_VIDEOS_BY_ID = 'getVideosById'
export const GET_VIDEOS_PAGE_TOKEN = 'getVideosPageToken'
export const GET_REGIONS = 'getRegions'
export const SEARCH_VIDEOS = 'searchVideos'
